### ISSUE TITLE
v0.19.0 Build Failed

### ISSUE THREAD

**Issue by krakow10** [AirenSoft/OvenMediaEngine#1915]
**Describe the bug**
Building the project fails.

**To Reproduce**
1. Begin with Ubuntu environment that worked for v0.17.3 (see https://github.com/AirenSoft/OvenMediaEngine/discussions/1755#discussioncomment-11675030)
2. Clone repo
3. `prerequisites.sh --enable-nvc`
4. `make -j16 release`
5. Observe error

**Expected behavior**
No build error

**Logs**
```
...
[545/549| 99%] [static] Linking libsrt_provider.a... => intermediates/RELEASE/static/libsrt_provider.a
[546/549| 99%] [static] Linking libmpegts_provider.a... => intermediates/RELEASE/static/libmpegts_provider.a
[547/549| 99%] [static] Linking libconfig.a... => intermediates/RELEASE/static/libconfig.a
[548/549| 99%] [executable] Linking OvenMediaEngine... => bin/RELEASE/OvenMediaEngine
/usr/bin/ld: cannot find -lnvidia-ml: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [core/build_executable.mk:9: bin/RELEASE/OvenMediaEngine] Error 1
```

**Server (please complete the following information):**
 - OS: Ubuntu 22.04.5 LTS
 - OvenMediaEngine Version: v0.19.0
 - Branch: v0.19.0 tag

**Player (please complete the following information):**
N/A

**Additional context**
There exist two .so files matching nvidia-ml.so*:
```
quat@ome-ubunter:/usr/lib/x86_64-linux-gnu$ ls libnvidia-ml.so.*
libnvidia-ml.so.1  libnvidia-ml.so.580.65.06
```
💡 Creating `libnvidia-ml.so` as a symbolic link to `libnvidia-ml.so.580.65.06` does complete the build:
```
sudo ln -s libnvidia-ml.so.580.65.06 libnvidia-ml.so
```
⚠️ But there are severe issues in the logs like `CUDA_ERROR_OUT_OF_MEMORY`, GPU vram is filled, the stream is delayed by 3 minutes, the stream intermittently cuts out, and one of the two push publishing streams doesn't work.

Here is the relevant server configuration and ovenmediaengine log:
[Server.xml](https://github.com/user-attachments/files/22105109/Server.xml.log)
[ovenmediaengine.log](https://github.com/user-attachments/files/22105110/ovenmediaengine.log)

I am observing the same build failure with v0.18.0 and even v0.17.3, so it's probably related to nvidia drivers.  I can also use the same symbolic link trick to get it to build and then get the same severe issues on these versions.

**Comment by Keukhan** [comment]
Hi @krakow10, 

Sorry for the late reply, and thanks for the report. I haven’t tested with NVIDIA Driver 580.x or higher yet.
I’ll check it to see what the problem is and what can be improved.

Thanks :)

**Comment by krakow10** [comment]
I cannot test if this still happens in the latest master due to another build issue, #1950.

**Comment by Keukhan** [comment]
@krakow10 
Please test again to see if the build still fails in your environment with the latest version.
In my development environment, it compiles successfully with the same 580 driver version.
If it still fails to compile, please check whether the library paths are properly configured as follows

````
soulk@OME-Dev:~/dev$ ldconfig -p | grep nvidia-ml
        libnvidia-ml.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-ml.so.1
        libnvidia-ml.so.1 (libc6) => /lib/i386-linux-gnu/libnvidia-ml.so.1
        libnvidia-ml.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-ml.so
        libnvidia-ml.so (libc6) => /lib/i386-linux-gnu/libnvidia-ml.so
soulk@OME-Dev:~/dev/OvenTranscoder/deploy/ovencoder3/ovencoder3_agent1$ 
````

````
soulk@OME-Dev:~/dev$for f in /etc/ld.so.conf.d/*.conf; do
>     echo "===== $f ====="
>     cat "$f"
>     echo
> done
===== /etc/ld.so.conf.d/000_cuda.conf =====
/usr/local/cuda/targets/x86_64-linux/lib

===== /etc/ld.so.conf.d/989_cuda-11.conf =====
/usr/local/cuda-11/targets/x86_64-linux/lib

===== /etc/ld.so.conf.d/fakeroot-x86_64-linux-gnu.conf =====
/usr/lib/x86_64-linux-gnu/libfakeroot

===== /etc/ld.so.conf.d/gds-11-8.conf =====
/usr/local/cuda-11.8/targets/x86_64-linux/lib

===== /etc/ld.so.conf.d/i386-linux-gnu.conf =====
# Multiarch support
/usr/local/lib/i386-linux-gnu
/lib/i386-linux-gnu
/usr/lib/i386-linux-gnu
/usr/local/lib/i686-linux-gnu
/lib/i686-linux-gnu
/usr/lib/i686-linux-gnu

===== /etc/ld.so.conf.d/libc.conf =====
# libc default configuration
/usr/local/lib

===== /etc/ld.so.conf.d/x86_64-linux-gnu.conf =====
# Multiarch support
/usr/local/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu

....
````

**Comment by krakow10** [comment]
Here is the library paths in ubuntu 22.04:
```
quat@ome-ubunter:~/OvenMediaEngine$ ldconfig -p | grep nvidia-ml
	libnvidia-ml.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-ml.so.1
```
```
quat@ome-ubunter:~/OvenMediaEngine$ for f in /etc/ld.so.conf.d/*.conf; do
     echo "===== $f ====="
     cat "$f"
     echo
 done
===== /etc/ld.so.conf.d/000_cuda.conf =====
/usr/local/cuda/targets/x86_64-linux/lib

===== /etc/ld.so.conf.d/989_cuda-11.conf =====
/usr/local/cuda-11/targets/x86_64-linux/lib

===== /etc/ld.so.conf.d/fakeroot-x86_64-linux-gnu.conf =====
/usr/lib/x86_64-linux-gnu/libfakeroot

===== /etc/ld.so.conf.d/gds-11-7.conf =====
/usr/local/cuda-11.7/targets/x86_64-linux/lib

===== /etc/ld.so.conf.d/gds-11-8.conf =====
/usr/local/cuda-11.8/targets/x86_64-linux/lib

===== /etc/ld.so.conf.d/libc.conf =====
# libc default configuration
/usr/local/lib

===== /etc/ld.so.conf.d/x86_64-linux-gnu.conf =====
# Multiarch support
/usr/local/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
```

I was not able to figure out how to install cuda 11.8 on ubuntu 22.04 properly.  I uninstalled `nvidia-cuda-toolkit` since it provides nvcc 11.5, and installed the package `cuda-toolkit-11-8` but the whisper build failed again with the following error:
```
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Including CPU backend
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native 
-- CUDA Toolkit found
-- Using CUDA architectures: 61;75;86
CMake Error at /usr/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:726 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/bin/nvcc

  Build flags:

  Id flags: -v

  

  The output was:

  No such file or directory

  

  

Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:6 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:48 (__determine_compiler_id_test)
  /usr/share/cmake-3.22/Modules/CMakeDetermineCUDACompiler.cmake:298 (CMAKE_DETERMINE_COMPILER_ID)
  ggml/src/ggml-cuda/CMakeLists.txt:41 (enable_language)


-- Configuring incomplete, errors occurred!
See also "/tmp/whisper/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/whisper/build/CMakeFiles/CMakeError.log".
(whisper) installation has failed.
```

It seems that it can't find nvcc 11.8 located at `/usr/local/cuda-11.8/bin/nvcc`.

**Comment by krakow10** [comment]
The project can be successfully built using the latest version, so technically this issue is resolved.  However, GPU acceleration is still unavailable, rendering the software unusable.

Log says "No supported NVIDIA accelerator":
```
[2026-01-13 21:57:01.129] I [OvenMediaEngine:443] Transcoder | transcoder_gpu.cpp:94   | Trying to release Transcoder GPU resources
[2026-01-13 21:57:01.129] I [OvenMediaEngine:443] Transcoder | transcoder_gpu.cpp:45   | Trying to check available hardware accelerators
[2026-01-13 21:57:01.391] W [OvenMediaEngine:443] Transcoder | transcoder_gpu.cpp:54   | No supported NVIDIA accelerator
```

In the same environment that previously worked https://github.com/AirenSoft/OvenMediaEngine/discussions/1755#discussioncomment-11675030

Nvidia driver version is now 590.48.01
